TestSite/mysite/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.maine, name='home'),
    path('about-me', views.about, name='about'),
    path('register', views.dj_register, name='register'),
    path('login', views.dj_login, name='login'),
    path('logout', views.dj_logout, name='logout'),
    path('user_list', views.get_user_list, name='user_list'),
    path('products', views.products, name='products'),
    path('products/<int:id>', views.product_detail,
         name='product_detail'),
    path('cart', views.cart_detail, name='cart_detail'),
    path('add/<int:id>/',
         views.cart_add,
         name='cart_add'),
    path('cart/remove/<int:id>/',
         views.cart_remove,
         name='cart_remove'),
]

TestSite/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TestSite/mysite/main/models.py
from django.db import models
from django_resized import ResizedImageField

class Prod(models.Model):
    name = models.CharField(max_length=200)
    price = models.IntegerField(blank=False)
    is_sale = models.BooleanField(default=False)
    sale_price = models.IntegerField(null=True, blank=True)
    description = models.CharField(max_length=500, blank=True)
    img = ResizedImageField(size=[600, 400],crop=['top','left'],upload_to='main/media/pictures', null=True, blank=True)
    
    def to_dict(self):
        return {
            'id': self.id,
            'name': self.name,
            'price': self.price,
            'is_sale': self.is_sale,
            'sale_price': self.sale_price,
            'description': self.description,
            'img': self.img
            # Добавьте другие поля, которые вам нужны
        }

TestSite/mysite/main/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

TestSite/mysite/main/views.py
import json
from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.views.decorators.http import require_POST

from .cart import Cart
from .forms import CartAddProductForm, CreateUserForm
from .models import Prod

def maine(request):
    last_id = Prod.objects.latest('id').id
    latest_products = [Prod.objects.get(id=last_id)]
    latest_products += [Prod.objects.get(id=last_id-1)]
    context = {
        'latest_products': latest_products
    }
    return render(request, 'main/index.html', context)


def about(request):
    return render(request, 'main/about.html')

def products(request):
    products = Prod.objects.all() 

    context = {'products': products}

    return render(request, 'main/products.html', context)

@login_required(login_url='login')
def get_user_list(request):
    from django.contrib.auth.models import User

    users = User.objects.all()
    context = {'users': users}

    return render(request, 'main/users_list.html', context)


def dj_register(request):
    form = CreateUserForm()

    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)

            return redirect('login')

    context = {
        'form': form,
        'form_name': 'Register Account',
        'info_text': 'Already have an account?',
        'info_url': 'login',
        'info_btn_text': 'Sign in'
    }
    return render(request, 'main/register.html', context)


def dj_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, 'Username or password is incorrect')

    context = {
        'form_name': 'Login',
        'info_text': 'Don\'t have an account?',
        'info_url': 'register',
        'info_btn_text': 'Sign up'
    }
    return render(request, 'main/login.html', context)


def dj_logout(request):
    logout(request)
    return redirect('home')

def product_detail(request, id):
    product = get_object_or_404(Prod, id=id)
    cart_product_form = CartAddProductForm()
    return render(request, 'main/detail.html', {'product': product, 'cart_product_form':cart_product_form})

@require_POST
def cart_add(request, id):
    cart = Cart(request)
    product = get_object_or_404(Prod, id=id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])

        response = {'data':cart.cart}
        
        return JsonResponse({'success':True, 'data':response})
    else: 
        return JsonResponse({'success':False, 'errors':"я хз"})


def cart_remove(request, id):
    cart = Cart(request)
    product = get_object_or_404(Prod, id=id)
    cart.remove(product)
    return redirect('cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'main/cart_detail.html', {'cart': cart})

TestSite/mysite/main/templates/main/about.html
{% extends 'main/base.html' %}

{% block title %}
    About me
{% endblock %}

{% block content %}
    <!-- Шапка страницы -->
<header class="py-3 bg-light">
    <div class="container">
      <h1 class="text-center">My page</h1>
    </div>
  </header>
  
  <!-- Основное содержимое страницы -->
  <main>
    <div class="container py-5">
      <div class="row">
        <!-- Блок с фотографией -->
        <div class="col-md-4 mb-4">
          <img src="main/media/pictures/batman.jpg" style="
            width: 220px; 
            height: 300px; 
            object-fit: cover;
            object-position: 50% 25%;"
            alt="My Photo" class="img-fluid">
        </div>
  
        <!-- Блок с описанием -->
        <div class="col-md-8">
          <h2>About me</h2>
          <p>I`m batman(for real)</p>
  
          <h2>My hobbies</h2>
          <ul>
            <li>Look at arts with femboys(often)</li>
            <li>Python Django(rarely)</li>
          </ul>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

TestSite/mysite/main/templates/main/base.html
<!doctype html>
<html lang="en">
<head>
  {% load static %}

    <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> -->

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    
    <title>{% block title %}MyTitle{% endblock %}</title>
    
    <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">-->
    

    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/js/dist/dropdown.js" integrity="sha512-z3wD4uJhOINo+Ou2vM5jS1dOJLhWnJ19cm+kx7tACOVn/2RMJW8MvL+irDpJL9AByH7V+vFvJxAt4+q3IL4u4Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> -->

    <!-- Favicon-->
    
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'home' %}">Test shop</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">About</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'products' %}">Products</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'user_list' %}">List of users</a></li>
            </ul>
            <a class="btn btn-outline-dark" href="cart">
                <i class="bi-cart-fill me-1"></i>
                Cart
                {% with total_items=cart|length %}
                <span class="badge bg-dark text-white ms-1 rounded-pill">{{total_items}}</span>
                {% endwith %}
            </a>
            <form method='post' action="{% url 'cart_remove' 3 %}">
                {%csrf_token%}
                <input type="submit" value="remode">
            </form>
            <ul class="navbar-nav ms-2 mt-2 mt-lg-0">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">Hello, {{request.user}} <a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'register' %}">Register</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container mt-5">
    {% block content %}
    <h1>Content</h1>
    {% endblock %}
</div>

<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; bebrashop 1939</p></div>
</footer>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script type="text/javascript" src="{% static 'js/main.js'%}"></script>
<style>
.card{
    cursor: pointer;
}
html, body {
  height: 100%;
  margin: 0;
}

body {
  display: flex;
  flex-direction: column;
}

.container{
  flex: 1;
}

footer {
  margin-top: 5%;
  flex-shrink: 0;
}
</style>
</body>
</html>

TestSite/mysite/main/templates/main/cart_detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
  Корзина покупок
{% endblock %}

{% block content %}
  <h1>Корзина покупок</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Картинка</th>
        <th>Товар</th>
        <th>Обновить кол-во</th>
        <th>Удалить</th>
        <th>Кол-во</th>
        <th>Цена за шт</th>
        <th>Общая стоимость</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
          <tr class="{{ item.id }}">
            <td>
              <a href="#">
                <img src="{{ item.img }}" style="width: 15%;">
              </a>
            </td>
            <td>{{ item.name }}</td>
            <td>
              <form class="updateForm" action="{% url 'cart_add' item.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url 'cart_remove' item.id %}">Удалить</a></td>
            <td class="quantity">
              {{ item.quantity }}
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
      {% endfor %}
      <tr class="total">
        <td>Всего</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'products' %}" class="button light">В магазин</a>
    <a href="#" class="button">Оформить заказ</a>
  </p>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
  $(".updateForm").each(function() {
    $(this).find("select").change(function() {
      updateCart($(this).closest(".updateForm"));
    });
  });

  function updateCart(form) {
    var formData = form.serialize();

    $.ajax({
      type: 'POST',
      url: form.attr('action'),
      data: formData,
      dataType: 'json',
      success: function(data) {

        $.ajax({
          type: 'GET',
          url: '/cart', // URL второго AJAX-запроса
          dataType: 'html',
          success: function(data) {
            console.log('Второй AJAX-запрос выполнен успешно.');
            console.log(data);

            // Здесь можете выполнить замену контента страницы
            $('body').html(data); // Пример замены контента, замените '#contentContainer' на ваш селектор

            // Или выполнить другие действия после успешного выполнения второго запроса
          },
          error: function(xhr, status, error) {
            console.log('Произошла ошибка при выполнении второго AJAX-запроса.');
            console.log(error);
          }
        });
      },
      error: function(xhr, status, error) {
        // Обработка ошибки запроса
        console.log("Произошла ошибка при отправке запроса.");
        console.log(error);
      }
    });
  }
});
</script>

{% endblock %}

TestSite/mysite/main/templates/main/detail.html
{% extends "main/base.html" %}
{% load static %}
{% block title %}
{{ product.name }}
{% endblock %}
{% block content %}
<div class="product-detail">
<img src="../{{ product.img }}">
<h1>{{ product.name }}</h1>
<h2>
<!-- <a href="{{ product.category.get_absolute_url }}">{{product.category }}</a> -->
</h2>
<p class="price">${{ product.price }}</p>
{{ product.description|linebreaks }}
<form method="post" action="{% url 'cart_add' product.id %}">
    {{ cart_product_form }}
    {%csrf_token%}
    <input class="btn btn-outline-dark mt-auto"type="submit" value="Add to cart">
</form>
</div>
{% endblock %}

TestSite/mysite/main/templates/main/form_base.html
<!DOCTYPE html>
<html>

<head>
	<title>{{ form_name }}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #fff !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #262626;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		.form-text{
			color: #fff;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #636363 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 class="form-text">{{ form_name }}</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% block form %}

						{% endblock %}
				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<button class="btn btn-default" type="submit">{{ form_name }}</button>
				   		</div>
					</form>
				</div>

				{% for message in messages %} <!-- костыль для стилей бутстрапа -->
					<p class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{message.tags}}{% endif %} mt-3">{{message}}</p>
				{% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						<p class="form-text" >{{ info_text }}  <a href="/{{ info_url }}" class="ml-2">{{ info_btn_text }}</a></p>
					</div>
				</div>
                {% block reg_status %}

                {% endblock %}
			</div>
		</div>
	</div>
	<script>
	{% block script%}

	{% endblock %}
	</script>
</body>
</html>

TestSite/mysite/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}
    Главная
{% endblock %}

{% block content %}
<!-- Основное содержимое страницы -->
<main>
  <div class="container py-5">
    <div class="row">
      <!-- Блок с баннером -->
      <div class="col-md-6 mb-4">
        <img src="https://via.placeholder.com/600x400" alt="Баннер" class="img-fluid">
        <p>*Фото класного, універсального магазину*</p>
      </div>

      <!-- Блок с новинками -->
      <div class="col-md-6 mb-4">
        <h2>Новинки</h2>
        <div class="row">
          {% for product in latest_products %}
            <div class="col-6">
              <div class="card" data-url="{{ product.id}}">
                <img src="{{product.img}}" alt="Фото товара" class="card-img-top">
                <div class="card-body">
                  <h5 class="card-title">{{product.name}}</h5>
                  {% if product.is_sale %} 
                    <span class="text-muted text-decoration-line-through">${{ product.price }}</span>
                    {{product.sale_price}}
                  {% else %}
                    <span class="card-text">${{product.price}}</span>
                  {% endif %}
                  <br><br>
                  <form class="text-center" method="post" action="{% url 'cart_add' product.id %}">
                    {{ cart_product_form }}
                    {%csrf_token%}
                    <select class="invisible" name="quantity" id="id_quantity">
                        <option value="1" selected>1</option>
                    <input class="btn btn-outline-dark mt-auto" type="submit" value="Add to cart">
                  </form>

                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

TestSite/mysite/main/templates/main/login.html
{% extends 'main/form_base.html' %}


{% block form %}
    {% csrf_token %}
    <div class="input-group mb-3">
        <div class="input-group-append">
            <span class="input-group-text"><i class="fas fa-user"></i></span>
        </div>
        <input type="text" class="form-control" name="username">
    </div>
    <div class="input-group mb-2">
        <div class="input-group-append">
            <span class="input-group-text"><i class="fas fa-key"></i></span>
        </div>
        <input type="password" class="form-control" name="password">
    </div>

{% endblock %}


{% block reg_status %}
    {% if form.errors %}
        <div class="mt-4">
            <div class="d-flex justify-content-center links">
                <span class="alert alert-danger m-2"> {{ form.errors }} </span>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block script%}
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder='Username...';
    form_fields[2].placeholder='Enter password...';


    for (var field in form_fields){
        form_fields[field].className += ' form-control'
    }
{% endblock %}

TestSite/mysite/main/templates/main/products.html
{% extends 'main/base.html' %}

{% block title %}
    Products
{% endblock %}

{% block content %}
<div class="container mb-10">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
    {% for product in products %}
        <div class="product-container">
            <div class="card" onclick="product_detail('products/{{ product.id }}')">
                <!-- Product image-->
                <img class="card-img-top" src="{{ product.img }}" alt="SYKAA" />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{product.name}}</h5>
                        <!-- Product price-->
                        {% if product.is_sale %} 
                            <span class="text-muted text-decoration-line-through">${{ product.price }}</span>
                            {{product.sale_price}}
                        {% else %}
                            <span>${{ product.price }}</span>
                        {% endif %}
                    </div>
                </div>
                <!--  Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <form class="updateForm" method="post" action="{% url 'cart_add' product.id %}">
                        {{ cart_product_form }}
                        {%csrf_token%}
                        <select class="invisible" name="quantity" id="id_quantity">
                            <option value="1" selected>1</option>
                        <input class="btn btn-outline-dark" type="submit" value="Add to cart">
                    </form>
                </div> 
            </div>
        </div>
    {% endfor %}
    </div>
</div>
{% endblock %}

TestSite/mysite/main/templates/main/register.html
{% extends 'main/form_base.html' %}


{% block form %}
    {% csrf_token %}
    <div class="input-group mb-3">
        <div class="input-group-append">
            <span class="input-group-text"><i class="fas fa-user"></i></span>
        </div>
        {{form.username}}
    </div>
    <div class="input-group mb-2">
        <div class="input-group-append">
            <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
        </div>
        {{form.email}}
    </div>
    <div class="input-group mb-2">
        <div class="input-group-append">
            <span class="input-group-text"><i class="fas fa-key"></i></span>
        </div>
        {{form.password1}}
    </div>
    <div class="input-group mb-2">
        <div class="input-group-append">
            <span class="input-group-text"><i class="fas fa-key"></i></span>
        </div>
        {{form.password2}}
    </div>
{% endblock %}


{% block reg_status %}
    {% if form.errors %}
        <div class="mt-4">
            <div class="d-flex justify-content-center links">
                <span class="alert alert-danger m-2"> {{ form.errors }} </span>
            </div>
        </div>
    {% endif %}
{% endblock %}


{% block script %}
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder='Username..';
    form_fields[2].placeholder='Email..';
    form_fields[3].placeholder='Enter password...';
    form_fields[4].placeholder='Re-enter Password...';


    for (var field in form_fields){
        form_fields[field].className += ' form-control'
    }
{% endblock %}

TestSite/mysite/main/templates/main/users_list.html
{% extends 'main/base.html' %}

{% block title %}
    List of users
{% endblock %}

{% block content %}

<div class="container mb-10">
  <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
    {% for user in users %}
      <div class="col mb-5">
        <div class="card h-100">
            <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">offline</div>
            <img class="card-img-top" src="https://www.transparentpng.com/thumb/user/gray-user-profile-icon-png-fP8Q1P.png" alt="..." />
            <div class="card-body p-4">
                <div class="text-center">
                    <h5 class="fw-bolder">{{user}}</h5>
                </div>
            </div>
            <!-- Product actions-->
            <!-- <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a></div>
            </div> -->
        </div>
    </div>
    {% endfor %}
  </div>
</div>



{% endblock %}